server:
  port: 8089

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:mysql://${REVIEW_DB_HOST:localhost}:${REVIEW_DB_PORT:3306}/${REVIEW_DB_NAME:skill_infinity_review}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${REVIEW_DB_USERNAME:root}
    password: ${REVIEW_DB_PASSWORD:Surya@2003}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /review-service/v3/api-docs
  swagger-ui:
    path: /review-service/swagger-ui.html

logging:
  level:
    com.skillinfinity: INFO
