export const adminKeys = {
  all: ['admin'] as const,
  dashboard: () => [...adminKeys.all, 'dashboard'] as const,
  analytics: () => [...adminKeys.all, 'analytics'] as const,
  users: (page: number, size: number) => [...adminKeys.all, 'users', page, size] as const,
  user: (userId: string) => [...adminKeys.all, 'user', userId] as const,
  mentors: (page: number, size: number) => [...adminKeys.all, 'mentors', page, size] as const,
  mentorApprovals: () => [...adminKeys.all, 'mentor-approvals'] as const,
  sessions: () => [...adminKeys.all, 'sessions'] as const,
  payments: () => [...adminKeys.all, 'payments'] as const,
  refunds: () => [...adminKeys.all, 'refunds'] as const,
  wallet: () => [...adminKeys.all, 'wallet'] as const,
  community: () => [...adminKeys.all, 'community'] as const,
  reviews: () => [...adminKeys.all, 'reviews'] as const,
  support: (status?: string) => [...adminKeys.all, 'support', status ?? 'all'] as const,
  ticket: (ticketId: string) => [...adminKeys.all, 'ticket', ticketId] as const,
  announcements: () => [...adminKeys.all, 'announcements'] as const,
  reports: () => [...adminKeys.all, 'reports'] as const,
  settings: () => [...adminKeys.all, 'settings'] as const,
  featureFlags: () => [...adminKeys.all, 'feature-flags'] as const,
  auditLogs: () => [...adminKeys.all, 'audit'] as const,
  monitoring: () => [...adminKeys.all, 'monitoring'] as const,
} as const;
