package com.skillinfinity.common.enums;

public enum ErrorCode {
    // Generic
    INTERNAL_ERROR,
    VALIDATION_ERROR,
    BAD_REQUEST,
    NOT_FOUND,
    CONFLICT,
    FORBIDDEN,
    UNAUTHORIZED,
    SERVICE_UNAVAILABLE,

    // Business
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    INVALID_STATE,
    OPERATION_NOT_ALLOWED,
    INSUFFICIENT_BALANCE,
    DUPLICATE_TRANSACTION,
    PAYMENT_FAILED,
    REFUND_NOT_ALLOWED,
    SUBSCRIPTION_EXPIRED,
    SESSION_EXPIRED,

    // Security
    INVALID_TOKEN,
    TOKEN_EXPIRED,
    ACCESS_DENIED,
    INVALID_CREDENTIALS,
    ACCOUNT_LOCKED,
    ACCOUNT_DISABLED,
    SENSITIVE_DATA_ERROR,

    // Communication
    EMAIL_SEND_FAILED,
    NOTIFICATION_FAILED,
    MESSAGE_SEND_FAILED,

    // External
    EXTERNAL_SERVICE_ERROR,
    DATABASE_ERROR,
    CACHE_ERROR,
    QUEUE_ERROR,
    STORAGE_ERROR
}
