import type {
  Achievement,
  ActivityItem,
  Community,
  CommunityCategory,
  CommunityComment,
  CommunityPost,
  LeaderboardCategory,
  LeaderboardEntry,
  LeaderboardRange,
  LearningStats,
  Review,
  Tag,
} from '@/types';

/* ============================================================
   Seed data for the Community Platform.
   Mirrors the community-service DTO shapes so the UI works fully
   offline and upgrades seamlessly to live API data.
   ============================================================ */

/** Current user identity used by the demo layer. */
export const CURRENT_USER_ID = 'u-me';
export const CURRENT_USER_NAME = 'Alex Morgan';

const hoursAgo = (hours: number): string => new Date(Date.now() - hours * 3_600_000).toISOString();
const daysAgo = (days: number): string => new Date(Date.now() - days * 86_400_000).toISOString();

/* ============================================================
   Categories & tags
   ============================================================ */

export const seedCategories: CommunityCategory[] = [
  { id: 'c-swe', name: 'Software Engineering', emoji: '💻', description: 'System design, architecture and engineering craft.', communityCount: 12 },
  { id: 'c-data', name: 'Data & AI', emoji: '🤖', description: 'Machine learning, data engineering and applied AI.', communityCount: 9 },
  { id: 'c-cloud', name: 'Cloud & DevOps', emoji: '☁️', description: 'AWS, Kubernetes, CI/CD and platform engineering.', communityCount: 7 },
  { id: 'c-career', name: 'Career & Leadership', emoji: '🚀', description: 'Interviews, promotions and leadership growth.', communityCount: 8 },
  { id: 'c-frontend', name: 'Frontend', emoji: '🎨', description: 'React, performance and modern web experiences.', communityCount: 6 },
  { id: 'c-security', name: 'Security', emoji: '🔐', description: 'AppSec, cryptography and secure engineering.', communityCount: 4 },
  { id: 'c-mobile', name: 'Mobile', emoji: '📱', description: 'iOS, Android and cross-platform development.', communityCount: 5 },
  { id: 'c-design', name: 'Design & UX', emoji: '✨', description: 'Product design, systems and research.', communityCount: 4 },
];

export const seedTags: Tag[] = [
  { name: 'system-design', count: 1284 },
  { name: 'react', count: 986 },
  { name: 'interview-prep', count: 874 },
  { name: 'career-growth', count: 651 },
  { name: 'kubernetes', count: 512 },
  { name: 'machine-learning', count: 493 },
  { name: 'java', count: 402 },
  { name: 'cloud', count: 376 },
  { name: 'resume-review', count: 301 },
  { name: 'study-plan', count: 264 },
  { name: 'mock-interview', count: 231 },
  { name: 'leadership', count: 187 },
];

/* ============================================================
   Communities
   ============================================================ */

const moderators = (names: Array<[string, string]>): Community['moderators'] =>
  names.map(([name, title], index) => ({
    id: `mod-${index}`,
    userId: `u-mod-${index}`,
    name,
    title,
    role: 'MODERATOR' as const,
    joinedAt: daysAgo(120 + index * 10),
  }));

const rules = (list: Array<[string, string]>): Community['rules'] =>
  list.map(([title, description], index) => ({ id: `rule-${index}`, title, description }));

export const seedCommunities: Community[] = [
  {
    id: 'comm-sd',
    name: 'System Design',
    slug: 'system-design',
    description: 'Whiteboard, discuss and master large-scale system design together.',
    longDescription:
      'The home for engineers preparing for senior system design rounds. Weekly whiteboard threads, trade-off breakdowns and mentorship-driven deep dives.',
    category: 'Software Engineering',
    tags: ['system-design', 'architecture', 'interview-prep'],
    emoji: '🏗️',
    coverIndex: 0,
    memberCount: 48210,
    postCount: 3204,
    onlineCount: 312,
    joined: true,
    isOfficial: true,
    pinnedPostIds: ['post-sd-1', 'post-sd-2'],
    moderators: moderators([['Alex Rivera', 'Staff Engineer · Mentor'], ['Maya Patel', 'Distributed Systems']]),
    rules: rules([
      ['Stay constructive', 'Critique designs, never people. Assume good intent.'],
      ['No leaked questions', 'Do not post live interview content.'],
      ['Mark your level', 'State whether you are practicing for L5 or staff-level rounds.'],
    ]),
    statistics: { postsThisWeek: 312, membersGrowth: 8.4, questionsAnswered: 1876, activeThisWeek: 9340 },
    createdAt: daysAgo(410),
  },
  {
    id: 'comm-java',
    name: 'Java & Spring',
    slug: 'java-spring',
    description: 'Enterprise Java, Spring Boot, microservices and clean architecture.',
    longDescription:
      'From monoliths to event-driven microservices — share code, ask questions and review each other’s Spring Boot architecture.',
    category: 'Software Engineering',
    tags: ['java', 'spring-boot', 'microservices'],
    emoji: '☕',
    coverIndex: 1,
    memberCount: 29180,
    postCount: 2150,
    onlineCount: 187,
    joined: false,
    moderators: moderators([['Sarah Chen', 'Backend Engineer · Mentor'], ['Omar Farouk', 'Kafka Enthusiast']]),
    rules: rules([
      ['Code with context', 'Include relevant snippets and what you have tried.'],
      ['Respect licensing', 'Do not share proprietary or licensed content.'],
    ]),
    statistics: { postsThisWeek: 198, membersGrowth: 5.1, questionsAnswered: 1204, activeThisWeek: 5620 },
    createdAt: daysAgo(380),
  },
  {
    id: 'comm-react',
    name: 'React & Frontend',
    slug: 'react-frontend',
    description: 'Rendering internals, performance and modern React engineering.',
    longDescription:
      'Profiling, memoization, streaming, RSC — everything about building delightful, fast interfaces with React.',
    category: 'Frontend',
    tags: ['react', 'typescript', 'performance'],
    emoji: '⚛️',
    coverIndex: 2,
    memberCount: 35640,
    postCount: 2864,
    onlineCount: 254,
    joined: true,
    isOfficial: true,
    pinnedPostIds: ['post-react-1'],
    moderators: moderators([['Emily Watson', 'Principal Engineer · Mentor'], ['Jonas Weber', 'TypeScript Wizard']]),
    rules: rules([
      ['Show the code', 'Provide runnable reproductions where possible.'],
      ['Talk metrics', 'Back performance claims with profiling numbers.'],
    ]),
    statistics: { postsThisWeek: 276, membersGrowth: 7.8, questionsAnswered: 1543, activeThisWeek: 8201 },
    createdAt: daysAgo(395),
  },
  {
    id: 'comm-ml',
    name: 'Machine Learning',
    slug: 'machine-learning',
    description: 'LLMs, RAG, training pipelines and ML career strategy.',
    longDescription:
      'From research papers to production systems. Discuss applied AI, evals, fine-tuning and breaking into ML.',
    category: 'Data & AI',
    tags: ['machine-learning', 'generative-ai', 'career-growth'],
    emoji: '🤖',
    coverIndex: 3,
    memberCount: 22140,
    postCount: 1498,
    onlineCount: 142,
    joined: false,
    moderators: moderators([['Priya Sharma', 'ML Engineer · Mentor'], ['Anika Rao', 'NLP Researcher']]),
    rules: rules([
      ['Beware hype', 'Ground claims in papers, benchmarks or shipping products.'],
      ['No homework help', 'This is a professional community, not a homework service.'],
    ]),
    statistics: { postsThisWeek: 167, membersGrowth: 12.3, questionsAnswered: 982, activeThisWeek: 4310 },
    createdAt: daysAgo(300),
  },
  {
    id: 'comm-career',
    name: 'Career & Leadership',
    slug: 'career-leadership',
    description: 'Interviews, promotion strategy and engineering leadership.',
    longDescription:
      'STAR stories, negotiation, managing up, and the leap from IC to manager — with mentors who have been there.',
    category: 'Career & Leadership',
    tags: ['career-growth', 'interview-prep', 'leadership'],
    emoji: '🚀',
    coverIndex: 4,
    memberCount: 31250,
    postCount: 2013,
    onlineCount: 208,
    joined: true,
    moderators: moderators([['David Kim', 'Engineering Manager · Mentor'], ['Sofia Marino', 'Leadership Coach']]),
    rules: rules([
      ['Be kind', 'Career pivots are vulnerable moments. Support, do not judge.'],
      ['No salary shaming', 'Compensation discussions stay respectful and factual.'],
    ]),
    statistics: { postsThisWeek: 243, membersGrowth: 6.2, questionsAnswered: 1411, activeThisWeek: 7180 },
    createdAt: daysAgo(360),
  },
  {
    id: 'comm-cloud',
    name: 'Cloud & DevOps',
    slug: 'cloud-devops',
    description: 'AWS, Kubernetes, IaC and platform engineering.',
    longDescription:
      'Design resilient platforms, automate everything and learn the operational craft behind modern infrastructure.',
    category: 'Cloud & DevOps',
    tags: ['kubernetes', 'cloud', 'devops'],
    emoji: '☁️',
    coverIndex: 5,
    memberCount: 18320,
    postCount: 1276,
    onlineCount: 96,
    joined: false,
    moderators: moderators([['Lena Fischer', 'Platform Engineer'], ['Victor Nguyen', 'SRE']]),
    rules: rules([
      ['No clickbait', 'Share real incidents, benchmarks and hard-won lessons.'],
      ['Pin the blast radius', 'Mark production-related threads clearly.'],
    ]),
    statistics: { postsThisWeek: 121, membersGrowth: 4.8, questionsAnswered: 764, activeThisWeek: 3120 },
    createdAt: daysAgo(280),
  },
  {
    id: 'comm-frontend',
    name: 'Frontend Performance',
    slug: 'frontend-performance',
    description: 'Web Vitals, rendering optimization and 60fps interfaces.',
    longDescription:
      'A focused community for profiling, bundling, hydration and every micro-interaction that makes UIs feel premium.',
    category: 'Frontend',
    tags: ['performance', 'react', 'web-vitals'],
    emoji: '⚡',
    coverIndex: 6,
    memberCount: 12480,
    postCount: 908,
    onlineCount: 71,
    joined: false,
    moderators: moderators([['Jonas Weber', 'TypeScript Wizard']]),
    rules: rules([
      ['Measure first', 'Always share before/after metrics.'],
    ]),
    statistics: { postsThisWeek: 88, membersGrowth: 3.9, questionsAnswered: 512, activeThisWeek: 2104 },
    createdAt: daysAgo(220),
  },
  {
    id: 'comm-security',
    name: 'Application Security',
    slug: 'app-security',
    description: 'AppSec, threat modeling and secure coding practices.',
    longDescription:
      'Learn to break and defend. Threat modeling, OWASP, and security engineering that ships.',
    category: 'Security',
    tags: ['security', 'appsec'],
    emoji: '🔐',
    coverIndex: 7,
    memberCount: 9860,
    postCount: 654,
    onlineCount: 44,
    joined: false,
    moderators: moderators([['Rahul Verma', 'Security Engineer']]),
    rules: rules([
      ['Responsible disclosure', 'Report responsibly; no live exploitation.'],
    ]),
    statistics: { postsThisWeek: 62, membersGrowth: 2.7, questionsAnswered: 331, activeThisWeek: 1450 },
    createdAt: daysAgo(190),
  },
];

/* ============================================================
   Posts
   ============================================================ */

export const seedPosts: CommunityPost[] = [
  {
    id: 'post-sd-1',
    communityId: 'comm-sd',
    communityName: 'System Design',
    communitySlug: 'system-design',
    authorId: 'u-001',
    authorName: 'Alex Rivera',
    authorTitle: 'Staff Engineer · Mentor',
    authorIsMentor: true,
    authorVerified: true,
    title: 'Designing a URL shortener: the trade-offs nobody talks about',
    content:
      'Everyone whiteboards the happy path. Let’s talk about the decisions that actually matter: ID generation under write spikes, redirect caching at the edge, and what happens when your analytics pipeline outgrows the URL table.\n\n**Key trade-off:** sequence vs UUID vs snowflake — and how each choice ripples into sharding.',
    contentType: 'TEXT',
    tags: ['system-design', 'interview-prep'],
    mentions: ['@maya-patel'],
    createdAt: hoursAgo(3),
    likeCount: 342,
    commentCount: 87,
    bookmarkCount: 214,
    shareCount: 96,
    viewCount: 12400,
    liked: true,
    bookmarked: true,
    pinned: true,
    trendingScore: 98,
  },
  {
    id: 'post-sd-2',
    communityId: 'comm-sd',
    communityName: 'System Design',
    communitySlug: 'system-design',
    authorId: 'u-maya',
    authorName: 'Maya Patel',
    authorTitle: 'Distributed Systems Engineer',
    authorIsMentor: false,
    content:
      'Which design would you pick for a real-time collaborative editor at 10M concurrent users? Cast your vote and justify it below 👇',
    contentType: 'POLL',
    poll: {
      id: 'poll-sd-2',
      question: 'Real-time collaborative editor — core sync strategy?',
      options: [
        { id: 'opt-1', text: 'OT (Operational Transformation)', votes: 412 },
        { id: 'opt-2', text: 'CRDTs (Conflict-free Replicated Data Types)', votes: 587 },
        { id: 'opt-3', text: 'Hybrid: OT for text, CRDT for presence', votes: 231 },
        { id: 'opt-4', text: 'Last-write-wins with optimistic UI', votes: 74 },
      ],
      totalVotes: 1304,
      votedOptionId: 'opt-2',
      expiresAt: daysAgo(-4),
    },
    tags: ['system-design', 'architecture'],
    createdAt: hoursAgo(7),
    likeCount: 198,
    commentCount: 64,
    bookmarkCount: 87,
    shareCount: 41,
    viewCount: 8600,
    liked: false,
    bookmarked: false,
    pinned: true,
    trendingScore: 91,
  },
  {
    id: 'post-react-1',
    communityId: 'comm-react',
    communityName: 'React & Frontend',
    communitySlug: 'react-frontend',
    authorId: 'u-002',
    authorName: 'Emily Watson',
    authorTitle: 'Principal Engineer · Mentor',
    authorIsMentor: true,
    authorVerified: true,
    title: 'A 7-step React performance checklist that actually ships',
    content:
      'I profiled 40+ production apps last year. These are the seven wins that mattered, in order:\n\n1. Kill waterfall requests (parallelize or preload)\n2. Memoize at the right boundary — not everywhere\n3. Virtualize the big lists\n4. Lazy-load below-the-fold routes\n5. Debounce expensive derived state\n6. Use transitions for heavy navigation\n7. Measure with real-user monitoring, not just Lighthouse\n\nHere’s the code pattern I use for the memoization boundary:',
    contentType: 'CODE',
    attachments: [
      {
        id: 'att-1',
        type: 'CODE',
        language: 'tsx',
        code: `const FeedList = memo(function FeedList({ items }: Props) {\n  const rendered = useMemo(\n    () => items.map((item) => <FeedRow key={item.id} item={item} />),\n    [items],\n  );\n  return <div className="feed">{rendered}</div>;\n});`,
      },
    ],
    tags: ['react', 'performance'],
    createdAt: hoursAgo(5),
    likeCount: 512,
    commentCount: 132,
    bookmarkCount: 389,
    shareCount: 204,
    viewCount: 19800,
    liked: true,
    bookmarked: true,
    pinned: false,
    trendingScore: 96,
  },
  {
    id: 'post-career-1',
    communityId: 'comm-career',
    communityName: 'Career & Leadership',
    communitySlug: 'career-leadership',
    authorId: 'u-004',
    authorName: 'David Kim',
    authorTitle: 'Engineering Manager · Mentor',
    authorIsMentor: true,
    authorVerified: true,
    content:
      'Preparing for behavioral interviews? Stop memorizing answers and start building a STAR story bank. One story per competency, told in 90 seconds. I wrote a free template — grab the link below and let me know what you think.',
    contentType: 'LINK',
    attachments: [
      {
        id: 'att-career-1',
        type: 'LINK',
        url: 'https://skillinfinity.io/templates/star-story-bank',
        title: 'The STAR Story Bank Template (Free)',
        provider: 'skillinfinity.io',
      },
    ],
    tags: ['interview-prep', 'career-growth'],
    createdAt: hoursAgo(9),
    likeCount: 274,
    commentCount: 58,
    bookmarkCount: 191,
    shareCount: 88,
    viewCount: 9200,
    liked: false,
    bookmarked: false,
    pinned: false,
    trendingScore: 84,
  },
  {
    id: 'post-java-1',
    communityId: 'comm-java',
    communityName: 'Java & Spring',
    communitySlug: 'java-spring',
    authorId: 'u-005',
    authorName: 'Sarah Chen',
    authorTitle: 'Backend Engineer · Mentor',
    authorIsMentor: true,
    authorVerified: false,
    title: 'From monolith to event-driven: our Kafka migration notes',
    content:
      'We moved 14 services onto event-driven communication last quarter. The single biggest lesson: **do not start with Kafka**. Start with an outbox pattern and a message broker you understand, then graduate.\n\nI shared our full migration checklist below.',
    contentType: 'DOCUMENT',
    attachments: [
      {
        id: 'att-java-1',
        type: 'DOCUMENT',
        fileName: 'kafka-migration-checklist.pdf',
        fileSize: 2_400_000,
        title: 'Kafka Migration Checklist',
      },
    ],
    tags: ['java', 'microservices'],
    createdAt: hoursAgo(14),
    likeCount: 189,
    commentCount: 47,
    bookmarkCount: 132,
    shareCount: 39,
    viewCount: 6400,
    liked: true,
    bookmarked: false,
    pinned: false,
    trendingScore: 76,
  },
  {
    id: 'post-ml-1',
    communityId: 'comm-ml',
    communityName: 'Machine Learning',
    communitySlug: 'machine-learning',
    authorId: 'u-003',
    authorName: 'Priya Sharma',
    authorTitle: 'ML Engineer · Mentor',
    authorIsMentor: true,
    authorVerified: true,
    title: 'RAG in production: the eval-first setup that caught 62% more hallucinations',
    content:
      'We built an eval harness before shipping RAG and it changed everything. Create 200 golden Q&A pairs, measure faithfulness + answer relevance, and gate every prompt change on the regression suite.',
    contentType: 'IMAGE',
    attachments: [
      {
        id: 'att-ml-1',
        type: 'IMAGE',
        url: 'https://picsum.photos/seed/rag-evals/1200/640',
        title: 'RAG eval regression dashboard',
      },
    ],
    tags: ['machine-learning', 'generative-ai'],
    createdAt: hoursAgo(18),
    likeCount: 428,
    commentCount: 96,
    bookmarkCount: 301,
    shareCount: 152,
    viewCount: 14100,
    liked: false,
    bookmarked: true,
    pinned: false,
    trendingScore: 88,
  },
  {
    id: 'post-cloud-1',
    communityId: 'comm-cloud',
    communityName: 'Cloud & DevOps',
    communitySlug: 'cloud-devops',
    authorId: 'u-lena',
    authorName: 'Lena Fischer',
    authorTitle: 'Platform Engineer',
    authorIsMentor: false,
    title: 'Kubernetes cost optimization: what actually moved the needle',
    content:
      'Turns out it wasn’t node sizing — it was **idle CPU requests**. Right-sizing requests cut our bill by 31% without a single pod restart. Details in the thread.',
    contentType: 'VIDEO',
    attachments: [
      {
        id: 'att-cloud-1',
        type: 'VIDEO',
        url: 'https://picsum.photos/seed/k8s-costs/1200/675',
        title: 'Watch: K8s cost optimization walkthrough',
        provider: 'skillinfinity.io',
      },
    ],
    tags: ['kubernetes', 'cloud'],
    createdAt: hoursAgo(26),
    likeCount: 156,
    commentCount: 38,
    bookmarkCount: 94,
    shareCount: 27,
    viewCount: 5200,
    liked: false,
    bookmarked: false,
    pinned: false,
    trendingScore: 69,
  },
  {
    id: 'post-fp-1',
    communityId: 'comm-frontend',
    communityName: 'Frontend Performance',
    communitySlug: 'frontend-performance',
    authorId: 'u-jonas',
    authorName: 'Jonas Weber',
    authorTitle: 'TypeScript Wizard',
    authorIsMentor: false,
    content:
      'Hot take: your LCP is a routing problem, not a CSS problem. Prefetch the next route on viewport idle. I saw INP drop from 420ms to 190ms with a 5-line idle callback.',
    contentType: 'TEXT',
    tags: ['performance', 'web-vitals'],
    createdAt: hoursAgo(30),
    likeCount: 231,
    commentCount: 52,
    bookmarkCount: 118,
    shareCount: 44,
    viewCount: 7300,
    liked: true,
    bookmarked: false,
    pinned: false,
    trendingScore: 72,
  },
  {
    id: 'post-sd-3',
    communityId: 'comm-sd',
    communityName: 'System Design',
    communitySlug: 'system-design',
    authorId: 'u-marcus',
    authorName: 'Marcus Reid',
    authorTitle: 'Data Analyst',
    authorIsMentor: false,
    content:
      'Week 3 of my system design study plan: completed my first full whiteboard with feedback. Sharing the template I used — feel free to copy and adapt it!',
    contentType: 'DOCUMENT',
    attachments: [
      {
        id: 'att-sd-3',
        type: 'DOCUMENT',
        fileName: 'whiteboard-template.docx',
        fileSize: 640_000,
        title: 'Whiteboard Practice Template',
      },
    ],
    tags: ['study-plan', 'system-design'],
    createdAt: daysAgo(1),
    likeCount: 84,
    commentCount: 21,
    bookmarkCount: 66,
    shareCount: 12,
    viewCount: 3100,
    liked: false,
    bookmarked: false,
    pinned: false,
    trendingScore: 58,
  },
  {
    id: 'post-ml-2',
    communityId: 'comm-ml',
    communityName: 'Machine Learning',
    communitySlug: 'machine-learning',
    authorId: 'u-anika',
    authorName: 'Anika Rao',
    authorTitle: 'NLP Researcher',
    authorIsMentor: false,
    content:
      'What’s everyone using for long-context evaluation? RAGAS? Custom faithfulness metrics? I’m building an eval suite for 200k-token contexts and would love battle-tested ideas.',
    contentType: 'TEXT',
    tags: ['machine-learning', 'generative-ai'],
    createdAt: daysAgo(1),
    likeCount: 67,
    commentCount: 34,
    bookmarkCount: 41,
    shareCount: 9,
    viewCount: 2400,
    liked: false,
    bookmarked: false,
    pinned: false,
    trendingScore: 54,
  },
  {
    id: 'post-react-2',
    communityId: 'comm-react',
    communityName: 'React & Frontend',
    communitySlug: 'react-frontend',
    authorId: 'u-jonas',
    authorName: 'Jonas Weber',
    authorTitle: 'TypeScript Wizard',
    authorIsMentor: false,
    title: 'Type-safe event emitters in TypeScript 5.x',
    content:
      'A tiny pattern for fully typed event buses — no more stringly-typed listeners:',
    contentType: 'CODE',
    attachments: [
      {
        id: 'att-react-2',
        type: 'CODE',
        language: 'typescript',
        code: `type Events = {\n  'post:liked': { postId: string; count: number };\n  'user:joined': { userId: string };\n};\n\nclass Emitter<T extends Record<string, unknown>> {\n  private handlers = new Map<keyof T, Set<(p: unknown) => void>>();\n\n  on<K extends keyof T>(event: K, fn: (payload: T[K]) => void) {\n    const set = this.handlers.get(event) ?? new Set();\n    set.add(fn as (p: unknown) => void);\n    this.handlers.set(event, set);\n  }\n\n  emit<K extends keyof T>(event: K, payload: T[K]) {\n    this.handlers.get(event)?.forEach((fn) => fn(payload));\n  }\n}`,
      },
    ],
    tags: ['typescript', 'react'],
    createdAt: daysAgo(2),
    likeCount: 143,
    commentCount: 29,
    bookmarkCount: 88,
    shareCount: 31,
    viewCount: 4800,
    liked: false,
    bookmarked: false,
    pinned: false,
    trendingScore: 62,
  },
  {
    id: 'post-career-2',
    communityId: 'comm-career',
    communityName: 'Career & Leadership',
    communitySlug: 'career-leadership',
    authorId: 'u-sofia',
    authorName: 'Sofia Marino',
    authorTitle: 'Leadership Coach',
    authorIsMentor: false,
    content:
      'Achieved a huge milestone this week — 100 mentees coached through promotion! If you are an IC thinking about the manager track, my inbox is open. Ask me anything in the comments 💬',
    contentType: 'TEXT',
    tags: ['leadership', 'career-growth'],
    createdAt: daysAgo(2),
    likeCount: 310,
    commentCount: 73,
    bookmarkCount: 52,
    shareCount: 61,
    viewCount: 9800,
    liked: true,
    bookmarked: false,
    pinned: false,
    trendingScore: 74,
  },
  {
    id: 'post-security-1',
    communityId: 'comm-security',
    communityName: 'Application Security',
    communitySlug: 'app-security',
    authorId: 'u-rahul',
    authorName: 'Rahul Verma',
    authorTitle: 'Security Engineer',
    authorIsMentor: false,
    content:
      'Threat modeling your auth flow? Start with the token lifecycle, not the login form. Where do tokens live, how do they rotate, and what happens on logout? Those three answers drive 80% of auth vulns.',
    contentType: 'TEXT',
    tags: ['security', 'appsec'],
    createdAt: daysAgo(3),
    likeCount: 96,
    commentCount: 18,
    bookmarkCount: 71,
    shareCount: 14,
    viewCount: 2900,
    liked: false,
    bookmarked: false,
    pinned: false,
    trendingScore: 47,
  },
  {
    id: 'post-me-1',
    authorId: CURRENT_USER_ID,
    authorName: CURRENT_USER_NAME,
    authorTitle: 'Full-stack Engineer',
    authorIsMentor: false,
    content:
      'Just completed my 5th session with Alex Rivera on system design — the whiteboard walkthrough of a distributed cache was *chef’s kiss*. Booking the interview prep session next week. 🎉',
    contentType: 'TEXT',
    tags: ['learning', 'system-design'],
    mentions: ['@alex-rivera'],
    createdAt: daysAgo(3),
    likeCount: 12,
    commentCount: 4,
    bookmarkCount: 0,
    shareCount: 1,
    viewCount: 180,
    liked: false,
    bookmarked: false,
    pinned: false,
    trendingScore: 20,
  },
  {
    id: 'post-me-2',
    authorId: CURRENT_USER_ID,
    authorName: CURRENT_USER_NAME,
    authorTitle: 'Full-stack Engineer',
    authorIsMentor: false,
    content:
      'My community leaderboard rank moved up 14 places this month! 🏆 The learning streak is real — consistency beats intensity.',
    contentType: 'TEXT',
    tags: ['learning', 'community'],
    createdAt: daysAgo(5),
    likeCount: 31,
    commentCount: 7,
    bookmarkCount: 2,
    shareCount: 3,
    viewCount: 420,
    liked: false,
    bookmarked: false,
    pinned: false,
    trendingScore: 26,
  },
];

/* ============================================================
   Comments (flat; tree is assembled in the UI)
   ============================================================ */

export const seedComments: Record<string, CommunityComment[]> = {
  'post-sd-1': [
    {
      id: 'c-sd-1',
      postId: 'post-sd-1',
      parentId: null,
      authorId: 'u-maya',
      authorName: 'Maya Patel',
      authorTitle: 'Distributed Systems Engineer',
      content: 'Great breakdown! The snowflake trade-off section finally made sharding click for me. Worth mentioning that UUIDv7 helps with time-ordering too.',
      reactions: [{ emoji: '👍', count: 24, reacted: true }, { emoji: '🔥', count: 9 }],
      likeCount: 48,
      liked: true,
      replyCount: 3,
      createdAt: hoursAgo(2),
    },
    {
      id: 'c-sd-1-1',
      postId: 'post-sd-1',
      parentId: 'c-sd-1',
      authorId: 'u-001',
      authorName: 'Alex Rivera',
      authorTitle: 'Staff Engineer · Mentor',
      authorIsMentor: true,
      content: 'Agreed on UUIDv7 — monotonic-ish IDs with zero coordination. Great call @maya-patel.',
      reactions: [{ emoji: '👍', count: 12 }],
      likeCount: 27,
      liked: false,
      replyCount: 0,
      createdAt: hoursAgo(1),
    },
    {
      id: 'c-sd-1-2',
      postId: 'post-sd-1',
      parentId: 'c-sd-1',
      authorId: 'u-marcus',
      authorName: 'Marcus Reid',
      authorTitle: 'Data Analyst',
      content: 'Would love a follow-up post on the analytics pipeline outgrowing the table — that bit hit home.',
      likeCount: 8,
      liked: false,
      replyCount: 0,
      createdAt: hoursAgo(1),
    },
    {
      id: 'c-sd-1-3',
      postId: 'post-sd-1',
      parentId: 'c-sd-1',
      authorId: 'u-lena',
      authorName: 'Lena Fischer',
      authorTitle: 'Platform Engineer',
      content: 'Bookmarked. The redirect caching discussion is exactly what I need for my L5 prep.',
      reactions: [{ emoji: '📌', count: 4 }],
      likeCount: 5,
      liked: false,
      replyCount: 0,
      createdAt: hoursAgo(0),
    },
    {
      id: 'c-sd-2',
      postId: 'post-sd-1',
      parentId: null,
      authorId: 'u-me',
      authorName: CURRENT_USER_NAME,
      authorTitle: 'Full-stack Engineer',
      content: 'This reframed how I think about ID generation under write spikes. Thank you! 🙌',
      reactions: [{ emoji: '❤️', count: 3 }],
      likeCount: 11,
      liked: false,
      replyCount: 0,
      createdAt: hoursAgo(1),
    },
  ],
  'post-react-1': [
    {
      id: 'c-react-1',
      postId: 'post-react-1',
      parentId: null,
      authorId: 'u-jonas',
      authorName: 'Jonas Weber',
      authorTitle: 'TypeScript Wizard',
      content: 'Point 4 (lazy-load below the fold) is so underrated. We saved 90KB of JS with route-level code splitting alone.',
      reactions: [{ emoji: '👍', count: 18 }],
      likeCount: 32,
      liked: false,
      replyCount: 1,
      createdAt: hoursAgo(4),
    },
    {
      id: 'c-react-1-1',
      postId: 'post-react-1',
      parentId: 'c-react-1',
      authorId: 'u-002',
      authorName: 'Emily Watson',
      authorTitle: 'Principal Engineer · Mentor',
      authorIsMentor: true,
      content: 'Exactly — and pair it with preload hints on the idle callback. Free wins.',
      likeCount: 14,
      liked: true,
      replyCount: 0,
      createdAt: hoursAgo(3),
    },
  ],
  'post-career-1': [
    {
      id: 'c-career-1',
      postId: 'post-career-1',
      parentId: null,
      authorId: 'u-sofia',
      authorName: 'Sofia Marino',
      authorTitle: 'Leadership Coach',
      content: 'The 90-second constraint is the secret. If you cannot tell it in 90 seconds, you have not distilled it yet.',
      reactions: [{ emoji: '🔥', count: 11 }],
      likeCount: 21,
      liked: false,
      replyCount: 0,
      createdAt: hoursAgo(8),
    },
  ],
  'post-ml-1': [
    {
      id: 'c-ml-1',
      postId: 'post-ml-1',
      parentId: null,
      authorId: 'u-anika',
      authorName: 'Anika Rao',
      authorTitle: 'NLP Researcher',
      content: 'Eval-first is the only way. Would you share how you built the golden set? 200 pairs is a great starting number.',
      likeCount: 17,
      liked: false,
      replyCount: 0,
      createdAt: hoursAgo(12),
    },
  ],
  'post-career-2': [
    {
      id: 'c-career-2',
      postId: 'post-career-2',
      parentId: null,
      authorId: 'u-me',
      authorName: CURRENT_USER_NAME,
      authorTitle: 'Full-stack Engineer',
      content: 'Congrats Sofia! 🎉 I’m an IC considering the manager track — what’s the first thing you recommend reading?',
      likeCount: 6,
      liked: false,
      replyCount: 1,
      createdAt: daysAgo(1),
    },
    {
      id: 'c-career-2-1',
      postId: 'post-career-2',
      parentId: 'c-career-2',
      authorId: 'u-sofia',
      authorName: 'Sofia Marino',
      authorTitle: 'Leadership Coach',
      content: 'Start with “The Manager’s Path”. Then shadow your skip-level for a month before committing. Happy to chat!',
      reactions: [{ emoji: '❤️', count: 7 }],
      likeCount: 19,
      liked: false,
      replyCount: 0,
      createdAt: daysAgo(1),
    },
  ],
  'post-me-1': [
    {
      id: 'c-me-1',
      postId: 'post-me-1',
      parentId: null,
      authorId: 'u-001',
      authorName: 'Alex Rivera',
      authorTitle: 'Staff Engineer · Mentor',
      authorIsMentor: true,
      content: 'Amazing progress, Alex! See you at the interview prep session. 💪',
      reactions: [{ emoji: '👏', count: 5 }],
      likeCount: 9,
      liked: true,
      replyCount: 0,
      createdAt: daysAgo(2),
    },
  ],
};

/* ============================================================
   Leaderboard
   ============================================================ */

const leaderboardNames: Array<[string, string, number]> = [
  ['Sarah Chen', 'Backend Engineer · Mentor', 4820],
  ['Priya Sharma', 'ML Engineer · Mentor', 4410],
  ['Marcus Reid', 'Data Analyst', 3980],
  ['Maya Patel', 'Distributed Systems Engineer', 3720],
  ['Jonas Weber', 'TypeScript Wizard', 3510],
  ['Lena Fischer', 'Platform Engineer', 3340],
  ['David Kim', 'Engineering Manager · Mentor', 3180],
  ['Anika Rao', 'NLP Researcher', 2970],
  ['Sofia Marino', 'Leadership Coach', 2760],
  ['Rahul Verma', 'Security Engineer', 2540],
  ['Emily Watson', 'Principal Engineer · Mentor', 2310],
  ['Omar Farouk', 'Kafka Enthusiast', 1980],
];

const buildLeaderboard = (category: LeaderboardCategory): LeaderboardEntry[] =>
  leaderboardNames.map(([name, title, points], index) => ({
    id: `${category}-${index}`,
    userId: `u-lb-${index}`,
    name,
    title,
    points: Math.round(points * (category === 'HELPFUL' ? 0.7 : category === 'CHAMPIONS' ? 0.85 : 1)),
    metric:
      category === 'LEARNERS'
        ? `${48 - index * 3} sessions`
        : category === 'MENTORS'
          ? `${36 - index * 2} sessions`
          : category === 'CONTRIBUTORS'
            ? `${120 - index * 8} contributions`
            : category === 'CHAMPIONS'
              ? `${14 - index} communities`
              : `${240 - index * 16} helpful votes`,
    badge:
      index === 0 ? '🥇' : index === 1 ? '🥈' : index === 2 ? '🥉' : undefined,
    change: ((index * 7) % 5) - 2,
    isCurrentUser: index === 3,
  }));

export const seedLeaderboard: Record<LeaderboardCategory, Record<LeaderboardRange, LeaderboardEntry[]>> = {
  LEARNERS: { WEEKLY: buildLeaderboard('LEARNERS'), MONTHLY: buildLeaderboard('LEARNERS'), ALL_TIME: buildLeaderboard('LEARNERS') },
  MENTORS: { WEEKLY: buildLeaderboard('MENTORS'), MONTHLY: buildLeaderboard('MENTORS'), ALL_TIME: buildLeaderboard('MENTORS') },
  CONTRIBUTORS: { WEEKLY: buildLeaderboard('CONTRIBUTORS'), MONTHLY: buildLeaderboard('CONTRIBUTORS'), ALL_TIME: buildLeaderboard('CONTRIBUTORS') },
  CHAMPIONS: { WEEKLY: buildLeaderboard('CHAMPIONS'), MONTHLY: buildLeaderboard('CHAMPIONS'), ALL_TIME: buildLeaderboard('CHAMPIONS') },
  HELPFUL: { WEEKLY: buildLeaderboard('HELPFUL'), MONTHLY: buildLeaderboard('HELPFUL'), ALL_TIME: buildLeaderboard('HELPFUL') },
};

/* ============================================================
   Learning activity & achievements
   ============================================================ */

export const seedActivity: ActivityItem[] = [
  { id: 'act-1', type: 'SESSION_COMPLETED', title: 'Completed System Design Deep Dive', description: '60-minute whiteboard session with Alex Rivera', points: 120, createdAt: hoursAgo(20), link: '/sessions/s-004', meta: 'System Design' },
  { id: 'act-2', type: 'ACHIEVEMENT', title: 'Unlocked “Streak Builder” badge', description: 'Maintained a 7-day learning streak', points: 50, createdAt: hoursAgo(26), link: '/community/achievements' },
  { id: 'act-3', type: 'POST', title: 'Shared a post in the community', description: '“Just completed my 5th session with Alex Rivera…”', points: 25, createdAt: daysAgo(1), link: '/community/posts/post-me-1' },
  { id: 'act-4', type: 'REVIEW', title: 'Left a 5-star review for Alex Rivera', description: 'Rated skill, communication and knowledge', points: 40, createdAt: daysAgo(1), link: '/mentors/m-001/reviews' },
  { id: 'act-5', type: 'BOOKMARK', title: 'Bookmarked “Designing a URL shortener”', description: 'Saved a post for later review', points: 5, createdAt: daysAgo(1), link: '/community/posts/post-sd-1' },
  { id: 'act-6', type: 'CERTIFICATE', title: 'Earned “System Design Foundations” certificate', description: 'Completed the guided learning path', points: 200, createdAt: daysAgo(3), link: '/community/achievements' },
  { id: 'act-7', type: 'MILESTONE', title: '10 sessions completed', description: 'Milestone reached — keep going!', points: 100, createdAt: daysAgo(4), link: '/sessions' },
  { id: 'act-8', type: 'COMMENT', title: 'Commented on “Career & Leadership” post', description: 'Asked about the IC → manager transition', points: 10, createdAt: daysAgo(5), link: '/community/posts/post-career-2' },
];

export const seedAchievements: Achievement[] = [
  { id: 'ach-1', type: 'BADGE', title: 'First Steps', description: 'Completed your first mentoring session', emoji: '👣', points: 50, rarity: 'COMMON', unlocked: true, unlockedAt: daysAgo(60) },
  { id: 'ach-2', type: 'STREAK', title: 'Streak Builder', description: 'Maintained a 7-day learning streak', emoji: '🔥', points: 100, rarity: 'RARE', unlocked: true, unlockedAt: daysAgo(9), progress: 12, total: 7 },
  { id: 'ach-3', type: 'BADGE', title: 'Community Voice', description: 'Published your first community post', emoji: '📣', points: 75, rarity: 'COMMON', unlocked: true, unlockedAt: daysAgo(30) },
  { id: 'ach-4', type: 'CERTIFICATE', title: 'System Design Foundations', description: 'Completed the guided learning path', emoji: '🏅', points: 200, rarity: 'EPIC', unlocked: true, unlockedAt: daysAgo(12) },
  { id: 'ach-5', type: 'CONTRIBUTION', title: 'Helping Hand', description: 'Left 5 helpful comments that earned upvotes', emoji: '🤝', points: 150, rarity: 'RARE', unlocked: true, unlockedAt: daysAgo(15), progress: 5, total: 5 },
  { id: 'ach-6', type: 'MILESTONE', title: 'Double Digits', description: 'Complete 10 mentoring sessions', emoji: '🎯', points: 120, rarity: 'EPIC', unlocked: true, unlockedAt: daysAgo(6), progress: 10, total: 10 },
  { id: 'ach-7', type: 'STREAK', title: 'Momentum', description: 'Maintain a 30-day learning streak', emoji: '⚡', points: 400, rarity: 'LEGENDARY', unlocked: false, progress: 12, total: 30 },
  { id: 'ach-8', type: 'BADGE', title: 'Review Star', description: 'Leave 10 verified reviews', emoji: '⭐', points: 180, rarity: 'EPIC', unlocked: false, progress: 6, total: 10 },
  { id: 'ach-9', type: 'CONTRIBUTION', title: 'Trend Setter', description: 'Write a post that reaches 100 likes', emoji: '📈', points: 250, rarity: 'LEGENDARY', unlocked: false, progress: 31, total: 100 },
  { id: 'ach-10', type: 'MILESTONE', title: 'Half Century', description: 'Complete 50 mentoring sessions', emoji: '💎', points: 600, rarity: 'LEGENDARY', unlocked: false, progress: 10, total: 50 },
  { id: 'ach-11', type: 'BADGE', title: 'Early Riser', description: 'Complete a session before 8 AM', emoji: '🌅', points: 80, rarity: 'RARE', unlocked: false, progress: 3, total: 5 },
  { id: 'ach-12', type: 'CERTIFICATE', title: 'Cloud Foundations', description: 'Complete the cloud learning path', emoji: '☁️', points: 200, rarity: 'EPIC', unlocked: false, progress: 7, total: 10 },
];

const contribution = (): Record<string, number> => {
  const map: Record<string, number> = {};
  const today = new Date();
  let seed = 42;
  const rand = () => {
    seed = (seed * 9301 + 49297) % 233280;
    return seed / 233280;
  };
  for (let day = 111; day >= 0; day -= 1) {
    const date = new Date(today);
    date.setDate(date.getDate() - day);
    const key = date.toISOString().slice(0, 10);
    const value = rand();
    map[key] = value > 0.62 ? 0 : value > 0.42 ? 1 : value > 0.22 ? 2 : 3 + Math.floor(rand() * 3);
  }
  return map;
};

export const seedLearningStats: LearningStats = {
  streakDays: 12,
  totalPoints: 3840,
  totalHours: 46.5,
  sessionsCompleted: 16,
  certificatesCount: 2,
  badgesCount: 4,
  postsCount: 6,
  reviewsCount: 5,
  weeklyProgress: [2, 3, 1, 4, 3, 5, 3],
  monthlyProgress: [8, 11, 9, 14, 12, 17, 15, 19, 16, 22, 18, 21, 24, 20, 23, 26, 22, 25, 28, 24, 27, 29, 25, 30, 27, 31, 33, 29, 32, 34],
  contribution: contribution(),
};

/* ============================================================
   Reviews (mentor review page + hub snippets)
   ============================================================ */

export const seedReviewsByMentor: Record<string, Review[]> = {
  'm-001': [
    {
      id: 'r-sd-1',
      mentorId: 'm-001',
      sessionId: 's-004',
      learnerId: 'u-me',
      learnerName: 'Alex Morgan',
      rating: 5,
      title: 'Transformative whiteboard sessions',
      content:
        'Alex breaks down system design better than any course I have taken. The mock interviews are incredibly realistic and the feedback is always actionable.',
      verified: true,
      dimensionRatings: { skill: 5, communication: 5, knowledge: 5, professionalism: 5 },
      helpfulCount: 24,
      notHelpfulCount: 1,
      votedByMe: false,
      replyCount: 1,
      createdAt: daysAgo(1),
      replies: [
        {
          id: 'rr-1',
          content: 'Thank you, Alex! Your whiteboard discipline made the difference. See you at the interview prep round!',
          createdAt: hoursAgo(22),
        },
      ],
    },
    {
      id: 'r-sd-2',
      mentorId: 'm-001',
      learnerId: 'u-7',
      learnerName: 'Sarah Chen',
      rating: 5,
      title: 'Game-changing session',
      content: 'Alex went beyond the slide and forced me to think in trade-offs. That alone was worth 10x the price.',
      verified: true,
      dimensionRatings: { skill: 5, communication: 4, knowledge: 5, professionalism: 5 },
      helpfulCount: 18,
      votedByMe: false,
      replyCount: 0,
      createdAt: daysAgo(8),
    },
    {
      id: 'r-sd-3',
      mentorId: 'm-001',
      learnerId: 'u-8',
      learnerName: 'Marcus Reid',
      rating: 4,
      title: 'Great depth, fast pace',
      content: 'Very deep on distributed systems. Pace is intense — come prepared or you will miss the nuance.',
      verified: true,
      dimensionRatings: { skill: 5, communication: 4, knowledge: 5, professionalism: 4 },
      helpfulCount: 9,
      votedByMe: false,
      replyCount: 0,
      createdAt: daysAgo(15),
    },
    {
      id: 'r-sd-4',
      mentorId: 'm-001',
      learnerId: 'u-9',
      learnerName: 'Priya Sharma',
      rating: 5,
      title: 'Worth every credit',
      content: 'Structured, rigorous and genuinely invested in my progress. The post-session notes are gold.',
      verified: true,
      anonymous: true,
      dimensionRatings: { skill: 5, communication: 5, knowledge: 5, professionalism: 5 },
      helpfulCount: 12,
      votedByMe: true,
      myVoteType: 'HELPFUL',
      replyCount: 0,
      createdAt: daysAgo(22),
    },
    {
      id: 'r-sd-5',
      mentorId: 'm-001',
      learnerId: 'u-10',
      learnerName: 'Omar Farouk',
      rating: 3,
      title: 'Strong mentor, packed schedule',
      content: 'The session quality is excellent but scheduling felt rigid. Would book again with more lead time.',
      verified: false,
      dimensionRatings: { skill: 4, communication: 4, knowledge: 4, professionalism: 3 },
      helpfulCount: 4,
      votedByMe: false,
      replyCount: 0,
      createdAt: daysAgo(30),
    },
    {
      id: 'r-sd-6',
      mentorId: 'm-001',
      learnerId: 'u-11',
      learnerName: 'Anika Rao',
      rating: 5,
      title: 'Interview prep that works',
      content: 'Went from freezing on whiteboard questions to running full mock rounds with confidence. Highly recommend.',
      verified: true,
      dimensionRatings: { skill: 5, communication: 5, knowledge: 5, professionalism: 5 },
      helpfulCount: 21,
      votedByMe: false,
      replyCount: 0,
      createdAt: daysAgo(41),
    },
  ],
  'm-002': [
    {
      id: 'r-react-1',
      mentorId: 'm-002',
      learnerId: 'u-12',
      learnerName: 'Jonas Weber',
      rating: 5,
      title: 'Performance mastery',
      content: 'Emily profiles in real time and explains the “why” behind every optimization. My INP dropped by half.',
      verified: true,
      dimensionRatings: { skill: 5, communication: 5, knowledge: 5, professionalism: 5 },
      helpfulCount: 15,
      votedByMe: false,
      replyCount: 0,
      createdAt: daysAgo(10),
    },
    {
      id: 'r-react-2',
      mentorId: 'm-002',
      learnerId: 'u-13',
      learnerName: 'Lena Fischer',
      rating: 4,
      title: 'Deep React internals',
      content: 'Very hands-on with DevTools. Would have liked more on RSC but the fundamentals were rock solid.',
      verified: true,
      dimensionRatings: { skill: 5, communication: 4, knowledge: 5, professionalism: 4 },
      helpfulCount: 7,
      votedByMe: false,
      replyCount: 0,
      createdAt: daysAgo(25),
    },
  ],
};

/* ============================================================
   Trending / quick stats for the hub
   ============================================================ */

export const seedHubStats = {
  totalMembers: 48210,
  totalMentors: 2500,
  postsThisWeek: 1204,
  questionsAnswered: 3876,
};

export const seedTrendingKeywords = [
  'system design',
  'react 19',
  'rag evals',
  'kubernetes',
  'behavioral prep',
  'typescript 5.8',
];
